SET client_encoding = 'UTF8';

DROP SCHEMA IF EXISTS dw CASCADE;
CREATE SCHEMA dw;
COMMENT ON SCHEMA dw IS 'Data Warehouse. Modelo dimensional (constelacao) da base Olist.';

CREATE OR REPLACE FUNCTION dw.fn_padroniza_texto(p_texto TEXT)
RETURNS TEXT
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT NULLIF(
             REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
               INITCAP(
                 regexp_replace(
                   translate(lower(trim(p_texto)),
                             'áàâãäéèêëíìîïóòôõöúùûüçñ',
                             'aaaaaeeeeiiiiooooouuuucn'),
                   '\s+', ' ', 'g')),
               ' Do ', ' do '), ' Da ', ' da '), ' De ', ' de '),
               ' Dos ', ' dos '), ' Das ', ' das '), ' E ', ' e '),
             '');
$$;
COMMENT ON FUNCTION dw.fn_padroniza_texto(TEXT) IS
    'Padroniza texto (trim, caixa, acentos e espacos) para atributos descritivos das dimensoes.';

CREATE TABLE dw.aux_uf_regiao (
    uf          CHAR(2)     PRIMARY KEY,
    nome_estado VARCHAR(30) NOT NULL,
    regiao      VARCHAR(15) NOT NULL
);
COMMENT ON TABLE dw.aux_uf_regiao IS 'Tabela auxiliar UF -> nome do estado e regiao geografica (IBGE).';

INSERT INTO dw.aux_uf_regiao (uf, nome_estado, regiao) VALUES
    ('AC', 'Acre',                'Norte'),
    ('AL', 'Alagoas',             'Nordeste'),
    ('AM', 'Amazonas',            'Norte'),
    ('AP', 'Amapá',               'Norte'),
    ('BA', 'Bahia',               'Nordeste'),
    ('CE', 'Ceará',               'Nordeste'),
    ('DF', 'Distrito Federal',    'Centro-Oeste'),
    ('ES', 'Espírito Santo',      'Sudeste'),
    ('GO', 'Goiás',               'Centro-Oeste'),
    ('MA', 'Maranhão',            'Nordeste'),
    ('MG', 'Minas Gerais',        'Sudeste'),
    ('MS', 'Mato Grosso do Sul',  'Centro-Oeste'),
    ('MT', 'Mato Grosso',         'Centro-Oeste'),
    ('PA', 'Pará',                'Norte'),
    ('PB', 'Paraíba',             'Nordeste'),
    ('PE', 'Pernambuco',          'Nordeste'),
    ('PI', 'Piauí',               'Nordeste'),
    ('PR', 'Paraná',              'Sul'),
    ('RJ', 'Rio de Janeiro',      'Sudeste'),
    ('RN', 'Rio Grande do Norte', 'Nordeste'),
    ('RO', 'Rondônia',            'Norte'),
    ('RR', 'Roraima',             'Norte'),
    ('RS', 'Rio Grande do Sul',   'Sul'),
    ('SC', 'Santa Catarina',      'Sul'),
    ('SE', 'Sergipe',             'Nordeste'),
    ('SP', 'São Paulo',           'Sudeste'),
    ('TO', 'Tocantins',           'Norte');

CREATE TABLE dw.dim_tempo (
    sk_tempo         INTEGER      PRIMARY KEY,
    data             DATE         NOT NULL UNIQUE,
    dia              SMALLINT     NOT NULL,
    mes              SMALLINT     NOT NULL,
    nome_mes         VARCHAR(10)  NOT NULL,
    mes_abrev        CHAR(3)      NOT NULL,
    trimestre        SMALLINT     NOT NULL,
    nome_trimestre   CHAR(6)      NOT NULL,
    semestre         SMALLINT     NOT NULL,
    ano              SMALLINT     NOT NULL,
    ano_mes          CHAR(7)      NOT NULL,
    dia_semana       SMALLINT     NOT NULL,
    nome_dia_semana  VARCHAR(15)  NOT NULL,
    fim_de_semana    BOOLEAN      NOT NULL
);
COMMENT ON TABLE dw.dim_tempo IS 'Dimensao tempo (calendario diario). SK no formato AAAAMMDD.';

CREATE TABLE dw.dim_cliente (
    sk_cliente          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_unique_id  CHAR(32)    NOT NULL UNIQUE,
    cep_prefixo         CHAR(5),
    cidade              VARCHAR(60),
    estado              CHAR(2),
    nome_estado         VARCHAR(30),
    regiao              VARCHAR(15),
    qtd_pedidos         SMALLINT    NOT NULL DEFAULT 0,
    flag_recorrente     BOOLEAN     NOT NULL DEFAULT FALSE
);
COMMENT ON TABLE dw.dim_cliente IS 'Dimensao cliente (um registro por customer_unique_id).';

CREATE TABLE dw.dim_produto (
    sk_produto          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id          CHAR(32)    NOT NULL UNIQUE,
    categoria_original  VARCHAR(60) NOT NULL,
    categoria           VARCHAR(60) NOT NULL,
    categoria_en        VARCHAR(60) NOT NULL,
    peso_g              INTEGER,
    comprimento_cm      SMALLINT,
    altura_cm           SMALLINT,
    largura_cm          SMALLINT,
    volume_cm3          INTEGER,
    faixa_peso          VARCHAR(20) NOT NULL,
    qtd_fotos           SMALLINT,
    tamanho_nome        SMALLINT,
    tamanho_descricao   SMALLINT
);
COMMENT ON TABLE dw.dim_produto IS 'Dimensao produto, com categoria padronizada/traduzida e faixa de peso.';

CREATE TABLE dw.dim_vendedor (
    sk_vendedor     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id       CHAR(32)    NOT NULL UNIQUE,
    cep_prefixo     CHAR(5),
    cidade          VARCHAR(60),
    estado          CHAR(2),
    nome_estado     VARCHAR(30),
    regiao          VARCHAR(15)
);
COMMENT ON TABLE dw.dim_vendedor IS 'Dimensao vendedor (seller) com localizacao padronizada.';

CREATE TABLE dw.dim_geografia (
    sk_geografia            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cep_prefixo             CHAR(5)     NOT NULL UNIQUE,
    cidade                  VARCHAR(60),
    estado                  CHAR(2),
    nome_estado             VARCHAR(30),
    regiao                  VARCHAR(15),
    latitude_media          NUMERIC(9,6),
    longitude_media         NUMERIC(9,6),
    qtd_registros_origem    INTEGER     NOT NULL DEFAULT 0,
    origem                  VARCHAR(30) NOT NULL
);
COMMENT ON TABLE dw.dim_geografia IS 'Dimensao geografia por prefixo de CEP, com coordenadas medias.';

CREATE TABLE dw.dim_pagamento (
    sk_pagamento             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_pagamento_original  VARCHAR(20) NOT NULL,
    tipo_pagamento           VARCHAR(30) NOT NULL,
    num_parcelas             SMALLINT    NOT NULL,
    faixa_parcelas           VARCHAR(20) NOT NULL,
    UNIQUE (tipo_pagamento_original, num_parcelas)
);
COMMENT ON TABLE dw.dim_pagamento IS 'Dimensao pagamento (tipo e numero de parcelas).';

CREATE TABLE dw.dim_status (
    sk_status         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_original   VARCHAR(20) NOT NULL UNIQUE,
    status_descricao  VARCHAR(30) NOT NULL,
    flag_entregue     BOOLEAN     NOT NULL,
    flag_cancelado    BOOLEAN     NOT NULL,
    ordem_ciclo       SMALLINT    NOT NULL
);
COMMENT ON TABLE dw.dim_status IS 'Dimensao status do pedido, com descricao em portugues e flags.';
